sudo: false

language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"
install:
    - pip install .
    - pip install -r dev-requirements.txt
    - pip install sphinx sphinx_rtd_theme
script:
    - flake8
    - env
    - black --check .
    - pytest
    - make doc

notifications:
  irc:
    channels:
    - "chat.freenode.net#python-effect"
    skip_join: true
    use_notice: true
    template:
      - "%{repository} %{branch} %{commit} by %{author}: %{message}  %{build_url}"
