sudo: false

language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.7"
    - "pypy"
install:
    - pip install .
    - pip install -r dev-requirements.txt
    - pip install sphinx sphinx_rtd_theme
script:
    - make lint
    - py.test
    - make doc

notifications:
  irc:
    channels:
    - "chat.freenode.net#python-effect"
    skip_join: true
    use_notice: true
    template:
      - "%{repository} %{branch} %{commit} by %{author}: %{message}  %{build_url}"
